baseURL = 'https://asapdiscovery.github.io'
languageCode = "en-us"
title = "ASAP Discovery Consortium"
theme = "kube"
description = "ASAP uses AI and structure-based approaches to deliever oral antivirals for viruses of pandemic concern which will be globally and equitably accessible"
Paginate = 4
publishDir = "./public"
pygmentsCodefences = true
pygmentsStyle = "colorful"

[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "https://github.com/asapdiscovery" # add your github profile name
  email = "john.chodera@choderalab.org"

[[menu.main]]
    name = "Science"
    weight = -60
    url = "/science/"
[[menu.main]]
    name = "Publications"
    weight = -50
    url = "/publications/"
[[menu.main]]
    name = "Members"
    weight = -30
    url = "/members/"
[[menu.main]]
    name = "Consortium"
    weight = -20
    url = "/consortium/"
[[menu.main]]
    name = "FAQ"
    weight = -10
    url = "/faq/"
[[menu.main]]
    name = "Jobs"
    weight = 0
    url = "/jobs/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
